CREATE TABLE IF NOT EXISTS projects(
    id integer primary key GENERATED BY DEFAULT AS IDENTITY,
    name text not null check (name <> ''),
    priority integer not null,
    descripcion text,
    delivery_date date not null
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer primary key GENERATED BY DEFAULT AS IDENTITY,
    name text not null check (name <> ''),
    done boolean,
    projectId integer references projects(id)
);

 -- INSERT PROJECTS DATA

INSERT INTO projects(name, priority, descripcion, delivery_date)
VALUES ('Make a web app 1', 1, 'Using Javascript', '2022-03-15');

INSERT INTO projects(name, priority, descripcion, delivery_date)
VALUES ('Make a web app 2', 2, 'Using Python', '2022-03-16');

INSERT INTO projects(name, priority, descripcion, delivery_date)
VALUES ('Make a web app 3', 3, 'Using Ruby And Rails', '2022-03-17');


 -- INSERT TASKS DATA
INSERT INTO tasks(name, done, projectId)
VALUES ('Download JavaScript', true, 1);

INSERT INTO tasks(name, done, projectId)
VALUES ('Download Python', true, 2);

INSERT INTO tasks(name, done, projectId)
VALUES ('Download Ruby and Rails', true, 3);